GET http://localhost:8201/eblog/authors

###
GET http://localhost:8201/eblog/authors/generic/findAll

###

GET http://localhost:8201/eblog/authors/generic/findById/2

###

PATCH http://localhost:8201/eblog/authors/1
Content-Type: application/json

{
  "name":"newName",
  "age":"12"
}






